[build]
  command = "rm -rf node_modules package-lock.json && npm install @rollup/rollup-linux-x64-gnu && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"
